flowchart LR

subgraph NODE["FL Node (IoT Edge)"]
A[Data Collector\nMicroservice\nIoT traffic / CIC-IoT-2023]
B[Preprocessor\nMicroservice\nCleaning / Scaling / Features]
C[FL Client\nMicroservice\nTinyML Training]

A --> B
B --> C
end

C -- gradients / weights --> S

subgraph SERVER["FL Server"]
S[Aggregation Engine\nFedAvg + QI Optimization]
end