global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "iot-node-1"
    static_configs:
      - targets: ["iot-node-1:8000"]
    metrics_path: "/metrics"

  - job_name: "traffic-generator"
    static_configs:
      - targets: ["traffic-generator:8000"]
    metrics_path: "/metrics"

  - job_name: "edge-ids-gateway"
    static_configs:
      - targets: ["edge-ids-gateway:8000"]
    metrics_path: "/metrics"
